import {InteractionsEnums} from './AppEnums';
import {imageRegistry} from './ImageRegistry';

export const singleSelectTitles = [
  'Type',
  'Zodiac',
  'Gender',
  'Education',
  'Dietary Preference',
  'Sexual Orientation',
  'Communication Style',
];

export const ItemsData = {
  Cannabis: ['Non-user', 'Occasional user', 'Regular user'],
  DietaryPreference: ['Omnivore', 'Vegetarian', 'Vegan', 'Kosher', 'Halal'],
  Drinking: ['Non-drinker', 'Social drinker', 'Heavy drinker'],
  Lifestyle: [
    'Early bird',
    'Night owl',
    'Introvert',
    'Extrovert',
    'Adventurous',
  ],
  Pets: [
    'Dog',
    'Cat',
    'Fish',
    'Bird',
    'Reptile',
    'Small furry animal',
    'No pets',
  ],
  SleepingHabits: [
    'Early riser',
    'Night owl',
    'Light sleeper',
    'Heavy sleeper',
  ],
  Smoking: ['Non-smoker', 'Occasional smoker', 'Regular smoker'],
  SocialMedia: [
    'Facebook',
    'Instagram',
    'Twitter',
    'Snapchat',
    'TikTok',
    'LinkedIn',
  ],
  Workout: [
    'Never',
    '1-2 times a week',
    '3-4 times a week',
    '5-6 times a week',
    'Every day',
  ],
  CovidVaccine: ['Fully vaccinated', 'Partially vaccinated', 'Not vaccinated'],
  Education: [
    'High School',
    'Some College',
    'Associate Degree',
    "Bachelor's Degree",
    "Master's Degree",
    'Doctorate Degree',
  ],
  FamilyPlans: ['Wants kids', "Doesn't want kids", 'Undecided'],
  Gender: ['Male', 'Female', 'Non-binary', 'Genderqueer', 'Other'],
  Interests: [
    'Sports',
    'Music',
    'Movies',
    'Reading',
    'Travel',
    'Food',
    'Fashion',
    'Art',
    'Gaming',
    'Technology',
    'Nature',
    'Photography',
    'Politics',
    'Animals',
    'Volunteering',
  ],
  RelationshipGoals: [
    'Long-term relationship',
    'Short-term relationship',
    'Marriage',
    'Friendship',
    'Companionship',
    'Casual dating',
  ],
  Zodiac: [
    'Aries',
    'Taurus',
    'Gemini',
    'Cancer',
    'Leo',
    'Virgo',
    'Libra',
    'Scorpio',
    'Sagittarius',
    'Capricorn',
    'Aquarius',
    'Pisces',
  ],
  CommunicationStyle: [
    'Direct',
    'Indirect',
    'Assertive',
    'Passive',
    'Aggressive',
  ],
  LoveStyle: ['Eros', 'Ludus', 'Storge', 'Pragma', 'Mania', 'Agape'],
  PersonalityType: [
    'INTJ',
    'INTP',
    'ENTJ',
    'ENTP',
    'INFJ',
    'INFP',
    'ENFJ',
    'ENFP',
    'ISTJ',
    'ISFJ',
    'ESTJ',
    'ESFJ',
    'ISTP',
    'ISFP',
    'ESTP',
    'ESFP',
  ],
};

export const HomeScreenUsersData = [
  {
    id: 35,
    name: 'John',
    age: '21',
    locationDistance: '25',
    picture: require('../assets/images/user8.jpg'),
  },
  {
    id: 20,
    name: 'Anna',
    age: '35',
    locationDistance: '30',
    picture: require('../assets/images/user2.jpg'),
  },
  {
    id: 18,
    name: 'Peter',
    age: '19',
    locationDistance: '40',
    picture: require('../assets/images/user3.jpg'),
  },
  {
    id: 24,
    name: 'Sarah',
    age: '32',
    locationDistance: '6',
    picture: require('../assets/images/user4.jpg'),
  },
  {
    id: 44,
    name: 'John',
    age: '28',
    locationDistance: '15',
    picture: require('../assets/images/user5.jpg'),
  },
  {
    id: 45,
    name: 'Sarah',
    age: '32',
    locationDistance: '6',
    picture: require('../assets/images/user6.jpg'),
  },
  {
    id: 46,
    name: 'John',
    age: '28',
    locationDistance: '15',
    picture: require('../assets/images/user7.jpg'),
  },
  {
    id: 47,
    name: 'John',
    age: '28',
    locationDistance: '15',
    picture: require('../assets/images/user1.jpg'),
  },
];

export const MessageData = [
  {
    id: 1,
    image: require('../assets/images/profilePicture.png'),
    name: 'Lindsey',
    message: 'Hey there, how are you?',
  },
  {
    id: 2,
    image: require('../assets/images/profilePicture.png'),
    name: 'Deidre',
    message: 'I just dropped my son at school.',
  },
  {
    id: 3,
    image: require('../assets/images/profilePicture.png'),
    name: 'Michael',
    message: 'What are you up to today?',
  },
  {
    id: 4,
    image: require('../assets/images/profilePicture.png'),
    name: 'Sophia',
    message: 'I have some errands to run later.',
  },
  {
    id: 5,
    image: require('../assets/images/profilePicture.png'),
    name: 'Ethan',
    message: 'That sounds good. Hope it goes well!',
  },
  {
    id: 6,
    image: require('../assets/images/profilePicture.png'),
    name: 'Olivia',
    message: 'Thanks! I’ll catch up with you later.',
  },
  {
    id: 7,
    image: require('../assets/images/profilePicture.png'),
    name: 'James',
    message: 'Looking forward to it.',
  },
  {
    id: 8,
    image: require('../assets/images/profilePicture.png'),
    name: 'Emma',
    message: 'Take care!',
  },
  {
    id: 9,
    image: require('../assets/images/profilePicture.png'),
    name: 'Liam',
    message: 'Talk to you soon!',
  },
  {
    id: 10,
    image: require('../assets/images/profilePicture.png'),
    name: 'Ava',
    message: 'See you later.',
  },
  {
    id: 11,
    image: require('../assets/images/profilePicture.png'),
    name: 'Noah',
    message: 'Bye for now!',
  },
  {
    id: 12,
    image: require('../assets/images/profilePicture.png'),
    name: 'Isabella',
    message: 'Goodbye!',
  },
  {
    id: 13,
    image: require('../assets/images/profilePicture.png'),
    name: 'Oliver',
    message: 'Are you free tomorrow?',
  },
  {
    id: 14,
    image: require('../assets/images/profilePicture.png'),
    name: 'Mia',
    message: 'Yes, I am! What’s the plan?',
  },
  {
    id: 15,
    image: require('../assets/images/profilePicture.png'),
    name: 'Jacob',
    message: 'I was thinking we could grab lunch.',
  },
  {
    id: 16,
    image: require('../assets/images/profilePicture.png'),
    name: 'Charlotte',
    message: 'That sounds like a great idea!',
  },
  {
    id: 17,
    image: require('../assets/images/profilePicture.png'),
    name: 'Michael',
    message: 'I’ll make a reservation then.',
  },
  {
    id: 18,
    image: require('../assets/images/profilePicture.png'),
    name: 'Amelia',
    message: 'Perfect, looking forward to it!',
  },
  {
    id: 19,
    image: require('../assets/images/profilePicture.png'),
    name: 'Lucas',
    message: 'See you tomorrow at noon.',
  },
  {
    id: 20,
    image: require('../assets/images/profilePicture.png'),
    name: 'Harper',
    message: 'Can’t wait! See you then.',
  },
];

export const countriesData = [
  {name: 'Afghanistan', code: 'AF'},
  {name: 'Åland Islands', code: 'AX'},
  {name: 'Albania', code: 'AL'},
  {name: 'Algeria', code: 'DZ'},
  {name: 'American Samoa', code: 'AS'},
  {name: 'AndorrA', code: 'AD'},
  {name: 'Angola', code: 'AO'},
  {name: 'Anguilla', code: 'AI'},
  {name: 'Antarctica', code: 'AQ'},
  {name: 'Antigua and Barbuda', code: 'AG'},
  {name: 'Argentina', code: 'AR'},
  {name: 'Armenia', code: 'AM'},
  {name: 'Aruba', code: 'AW'},
  {name: 'Australia', code: 'AU'},
  {name: 'Austria', code: 'AT'},
  {name: 'Azerbaijan', code: 'AZ'},
  {name: 'Bahamas', code: 'BS'},
  {name: 'Bahrain', code: 'BH'},
  {name: 'Bangladesh', code: 'BD'},
  {name: 'Barbados', code: 'BB'},
  {name: 'Belarus', code: 'BY'},
  {name: 'Belgium', code: 'BE'},
  {name: 'Belize', code: 'BZ'},
  {name: 'Benin', code: 'BJ'},
  {name: 'Bermuda', code: 'BM'},
  {name: 'Bhutan', code: 'BT'},
  {name: 'Bolivia', code: 'BO'},
  {name: 'Bosnia and Herzegovina', code: 'BA'},
  {name: 'Botswana', code: 'BW'},
  {name: 'Bouvet Island', code: 'BV'},
  {name: 'Brazil', code: 'BR'},
  {name: 'British Indian Ocean Territory', code: 'IO'},
  {name: 'Brunei Darussalam', code: 'BN'},
  {name: 'Bulgaria', code: 'BG'},
  {name: 'Burkina Faso', code: 'BF'},
  {name: 'Burundi', code: 'BI'},
  {name: 'Cambodia', code: 'KH'},
  {name: 'Cameroon', code: 'CM'},
  {name: 'Canada', code: 'CA'},
  {name: 'Cape Verde', code: 'CV'},
  {name: 'Cayman Islands', code: 'KY'},
  {name: 'Central African Republic', code: 'CF'},
  {name: 'Chad', code: 'TD'},
  {name: 'Chile', code: 'CL'},
  {name: 'China', code: 'CN'},
  {name: 'Christmas Island', code: 'CX'},
  {name: 'Cocos (Keeling) Islands', code: 'CC'},
  {name: 'Colombia', code: 'CO'},
  {name: 'Comoros', code: 'KM'},
  {name: 'Congo', code: 'CG'},
  {name: 'Congo, The Democratic Republic of the', code: 'CD'},
  {name: 'Cook Islands', code: 'CK'},
  {name: 'Costa Rica', code: 'CR'},
  {name: "Cote D'Ivoire", code: 'CI'},
  {name: 'Croatia', code: 'HR'},
  {name: 'Cuba', code: 'CU'},
  {name: 'Cyprus', code: 'CY'},
  {name: 'Czech Republic', code: 'CZ'},
  {name: 'Denmark', code: 'DK'},
  {name: 'Djibouti', code: 'DJ'},
  {name: 'Dominica', code: 'DM'},
  {name: 'Dominican Republic', code: 'DO'},
  {name: 'Ecuador', code: 'EC'},
  {name: 'Egypt', code: 'EG'},
  {name: 'El Salvador', code: 'SV'},
  {name: 'Equatorial Guinea', code: 'GQ'},
  {name: 'Eritrea', code: 'ER'},
  {name: 'Estonia', code: 'EE'},
  {name: 'Ethiopia', code: 'ET'},
  {name: 'Falkland Islands (Malvinas)', code: 'FK'},
  {name: 'Faroe Islands', code: 'FO'},
  {name: 'Fiji', code: 'FJ'},
  {name: 'Finland', code: 'FI'},
  {name: 'France', code: 'FR'},
  {name: 'French Guiana', code: 'GF'},
  {name: 'French Polynesia', code: 'PF'},
  {name: 'French Southern Territories', code: 'TF'},
  {name: 'Gabon', code: 'GA'},
  {name: 'Gambia', code: 'GM'},
  {name: 'Georgia', code: 'GE'},
  {name: 'Germany', code: 'DE'},
  {name: 'Ghana', code: 'GH'},
  {name: 'Gibraltar', code: 'GI'},
  {name: 'Greece', code: 'GR'},
  {name: 'Greenland', code: 'GL'},
  {name: 'Grenada', code: 'GD'},
  {name: 'Guadeloupe', code: 'GP'},
  {name: 'Guam', code: 'GU'},
  {name: 'Guatemala', code: 'GT'},
  {name: 'Guernsey', code: 'GG'},
  {name: 'Guinea', code: 'GN'},
  {name: 'Guinea-Bissau', code: 'GW'},
  {name: 'Guyana', code: 'GY'},
  {name: 'Haiti', code: 'HT'},
  {name: 'Heard Island and Mcdonald Islands', code: 'HM'},
  {name: 'Holy See (Vatican City State)', code: 'VA'},
  {name: 'Honduras', code: 'HN'},
  {name: 'Hong Kong', code: 'HK'},
  {name: 'Hungary', code: 'HU'},
  {name: 'Iceland', code: 'IS'},
  {name: 'India', code: 'IN'},
  {name: 'Indonesia', code: 'ID'},
  {name: 'Iran, Islamic Republic Of', code: 'IR'},
  {name: 'Iraq', code: 'IQ'},
  {name: 'Ireland', code: 'IE'},
  {name: 'Isle of Man', code: 'IM'},
  {name: 'Israel', code: 'IL'},
  {name: 'Italy', code: 'IT'},
  {name: 'Jamaica', code: 'JM'},
  {name: 'Japan', code: 'JP'},
  {name: 'Jersey', code: 'JE'},
  {name: 'Jordan', code: 'JO'},
  {name: 'Kazakhstan', code: 'KZ'},
  {name: 'Kenya', code: 'KE'},
  {name: 'Kiribati', code: 'KI'},
  {name: "Korea, Democratic People'S Republic of", code: 'KP'},
  {name: 'Korea, Republic of', code: 'KR'},
  {name: 'Kuwait', code: 'KW'},
  {name: 'Kyrgyzstan', code: 'KG'},
  {name: "Lao People'S Democratic Republic", code: 'LA'},
  {name: 'Latvia', code: 'LV'},
  {name: 'Lebanon', code: 'LB'},
  {name: 'Lesotho', code: 'LS'},
  {name: 'Liberia', code: 'LR'},
  {name: 'Libyan Arab Jamahiriya', code: 'LY'},
  {name: 'Liechtenstein', code: 'LI'},
  {name: 'Lithuania', code: 'LT'},
  {name: 'Luxembourg', code: 'LU'},
  {name: 'Macao', code: 'MO'},
  {name: 'Macedonia, The Former Yugoslav Republic of', code: 'MK'},
  {name: 'Madagascar', code: 'MG'},
  {name: 'Malawi', code: 'MW'},
  {name: 'Malaysia', code: 'MY'},
  {name: 'Maldives', code: 'MV'},
  {name: 'Mali', code: 'ML'},
  {name: 'Malta', code: 'MT'},
  {name: 'Marshall Islands', code: 'MH'},
  {name: 'Martinique', code: 'MQ'},
  {name: 'Mauritania', code: 'MR'},
  {name: 'Mauritius', code: 'MU'},
  {name: 'Mayotte', code: 'YT'},
  {name: 'Mexico', code: 'MX'},
  {name: 'Micronesia, Federated States of', code: 'FM'},
  {name: 'Moldova, Republic of', code: 'MD'},
  {name: 'Monaco', code: 'MC'},
  {name: 'Mongolia', code: 'MN'},
  {name: 'Montserrat', code: 'MS'},
  {name: 'Morocco', code: 'MA'},
  {name: 'Mozambique', code: 'MZ'},
  {name: 'Myanmar', code: 'MM'},
  {name: 'Namibia', code: 'NA'},
  {name: 'Nauru', code: 'NR'},
  {name: 'Nepal', code: 'NP'},
  {name: 'Netherlands', code: 'NL'},
  {name: 'Netherlands Antilles', code: 'AN'},
  {name: 'New Caledonia', code: 'NC'},
  {name: 'New Zealand', code: 'NZ'},
  {name: 'Nicaragua', code: 'NI'},
  {name: 'Niger', code: 'NE'},
  {name: 'Nigeria', code: 'NG'},
  {name: 'Niue', code: 'NU'},
  {name: 'Norfolk Island', code: 'NF'},
  {name: 'Northern Mariana Islands', code: 'MP'},
  {name: 'Norway', code: 'NO'},
  {name: 'Oman', code: 'OM'},
  {name: 'Pakistan', code: 'PK'},
  {name: 'Palau', code: 'PW'},
  {name: 'Palestinian Territory, Occupied', code: 'PS'},
  {name: 'Panama', code: 'PA'},
  {name: 'Papua New Guinea', code: 'PG'},
  {name: 'Paraguay', code: 'PY'},
  {name: 'Peru', code: 'PE'},
  {name: 'Philippines', code: 'PH'},
  {name: 'Pitcairn', code: 'PN'},
  {name: 'Poland', code: 'PL'},
  {name: 'Portugal', code: 'PT'},
  {name: 'Puerto Rico', code: 'PR'},
  {name: 'Qatar', code: 'QA'},
  {name: 'Reunion', code: 'RE'},
  {name: 'Romania', code: 'RO'},
  {name: 'Russian Federation', code: 'RU'},
  {name: 'RWANDA', code: 'RW'},
  {name: 'Saint Helena', code: 'SH'},
  {name: 'Saint Kitts and Nevis', code: 'KN'},
  {name: 'Saint Lucia', code: 'LC'},
  {name: 'Saint Pierre and Miquelon', code: 'PM'},
  {name: 'Saint Vincent and the Grenadines', code: 'VC'},
  {name: 'Samoa', code: 'WS'},
  {name: 'San Marino', code: 'SM'},
  {name: 'Sao Tome and Principe', code: 'ST'},
  {name: 'Saudi Arabia', code: 'SA'},
  {name: 'Senegal', code: 'SN'},
  {name: 'Serbia and Montenegro', code: 'CS'},
  {name: 'Seychelles', code: 'SC'},
  {name: 'Sierra Leone', code: 'SL'},
  {name: 'Singapore', code: 'SG'},
  {name: 'Slovakia', code: 'SK'},
  {name: 'Slovenia', code: 'SI'},
  {name: 'Solomon Islands', code: 'SB'},
  {name: 'Somalia', code: 'SO'},
  {name: 'South Africa', code: 'ZA'},
  {name: 'South Georgia and the South Sandwich Islands', code: 'GS'},
  {name: 'Spain', code: 'ES'},
  {name: 'Sri Lanka', code: 'LK'},
  {name: 'Sudan', code: 'SD'},
  {name: 'Suriname', code: 'SR'},
  {name: 'Svalbard and Jan Mayen', code: 'SJ'},
  {name: 'Swaziland', code: 'SZ'},
  {name: 'Sweden', code: 'SE'},
  {name: 'Switzerland', code: 'CH'},
  {name: 'Syrian Arab Republic', code: 'SY'},
  {name: 'Taiwan, Province of China', code: 'TW'},
  {name: 'Tajikistan', code: 'TJ'},
  {name: 'Tanzania, United Republic of', code: 'TZ'},
  {name: 'Thailand', code: 'TH'},
  {name: 'Timor-Leste', code: 'TL'},
  {name: 'Togo', code: 'TG'},
  {name: 'Tokelau', code: 'TK'},
  {name: 'Tonga', code: 'TO'},
  {name: 'Trinidad and Tobago', code: 'TT'},
  {name: 'Tunisia', code: 'TN'},
  {name: 'Turkey', code: 'TR'},
  {name: 'Turkmenistan', code: 'TM'},
  {name: 'Turks and Caicos Islands', code: 'TC'},
  {name: 'Tuvalu', code: 'TV'},
  {name: 'Uganda', code: 'UG'},
  {name: 'Ukraine', code: 'UA'},
  {name: 'United Arab Emirates', code: 'AE'},
  {name: 'United Kingdom', code: 'GB'},
  {name: 'United States', code: 'US'},
  {name: 'United States Minor Outlying Islands', code: 'UM'},
  {name: 'Uruguay', code: 'UY'},
  {name: 'Uzbekistan', code: 'UZ'},
  {name: 'Vanuatu', code: 'VU'},
  {name: 'Venezuela', code: 'VE'},
  {name: 'Viet Nam', code: 'VN'},
  {name: 'Virgin Islands, British', code: 'VG'},
  {name: 'Virgin Islands, U.S.', code: 'VI'},
  {name: 'Wallis and Futuna', code: 'WF'},
  {name: 'Western Sahara', code: 'EH'},
  {name: 'Yemen', code: 'YE'},
  {name: 'Zambia', code: 'ZM'},
  {name: 'Zimbabwe', code: 'ZW'},
];

export const languagesData: Record<string, string> = {
  aa: 'Afar',
  ab: 'Abkhazian',
  ae: 'Avestan',
  af: 'Afrikaans',
  ak: 'Akan',
  am: 'Amharic',
  an: 'Aragonese',
  ar: 'Arabic',
  as: 'Assamese',
  av: 'Avaric',
  ay: 'Aymara',
  az: 'Azerbaijani',
  ba: 'Bashkir',
  be: 'Belarusian',
  bg: 'Bulgarian',
  bi: 'Bislama',
  bm: 'Bambara',
  bn: 'Bengali',
  bo: 'Tibetan',
  br: 'Breton',
  bs: 'Bosnian',
  ca: 'Catalan',
  ce: 'Chechen',
  ch: 'Chamorro',
  co: 'Corsican',
  cr: 'Cree',
  cs: 'Czech',
  cu: 'Church Slavic',
  cv: 'Chuvash',
  cy: 'Welsh',
  da: 'Danish',
  de: 'German',
  dv: 'Divehi',
  dz: 'Dzongkha',
  ee: 'Ewe',
  el: 'Greek',
  en: 'English',
  eo: 'Esperanto',
  es: 'Spanish',
  et: 'Estonian',
  eu: 'Basque',
  fa: 'Persian',
  ff: 'Fulah',
  fi: 'Finnish',
  fj: 'Fijian',
  fo: 'Faroese',
  fr: 'French',
  fy: 'Western Frisian',
  ga: 'Irish',
  gd: 'Gaelic',
  gl: 'Galician',
  gn: 'Guarani',
  gu: 'Gujarati',
  gv: 'Manx',
  ha: 'Hausa',
  he: 'Hebrew',
  hi: 'Hindi',
  ho: 'Hiri Motu',
  hr: 'Croatian',
  ht: 'Haitian',
  hu: 'Hungarian',
  hy: 'Armenian',
  hz: 'Herero',
  ia: 'Interlingua',
  id: 'Indonesian',
  ie: 'Interlingue',
  ig: 'Igbo',
  ii: 'Sichuan Yi',
  ik: 'Inupiaq',
  io: 'Ido',
  is: 'Icelandic',
  it: 'Italian',
  iu: 'Inuktitut',
  ja: 'Japanese',
  jv: 'Javanese',
  ka: 'Georgian',
  kg: 'Kongo',
  ki: 'Kikuyu',
  kj: 'Kuanyama',
  kk: 'Kazakh',
  kl: 'Kalaallisut',
  km: 'Central Khmer',
  kn: 'Kannada',
  ko: 'Korean',
  kr: 'Kanuri',
  ks: 'Kashmiri',
  ku: 'Kurdish',
  kv: 'Komi',
  kw: 'Cornish',
  ky: 'Kirghiz',
  la: 'Latin',
  lb: 'Luxembourgish',
  lg: 'Ganda',
  li: 'Limburgan',
  ln: 'Lingala',
  lo: 'Lao',
  lt: 'Lithuanian',
  lu: 'Luba-Katanga',
  lv: 'Latvian',
  mg: 'Malagasy',
  mh: 'Marshallese',
  mi: 'Maori',
  mk: 'Macedonian',
  ml: 'Malayalam',
  mn: 'Mongolian',
  mr: 'Marathi',
  ms: 'Malay',
  mt: 'Maltese',
  my: 'Burmese',
  na: 'Nauru',
  nb: 'Bokmål, Norwegian',
  nd: 'Ndebele, North',
  ne: 'Nepali',
  ng: 'Ndonga',
  nl: 'Dutch',
  nn: 'Norwegian Nynorsk',
  no: 'Norwegian',
  nr: 'Ndebele, South',
  nv: 'Navajo',
  ny: 'Chichewa',
  oc: 'Occitan',
  oj: 'Ojibwa',
  om: 'Oromo',
  or: 'Oriya',
  os: 'Ossetian',
  pa: 'Panjabi',
  pi: 'Pali',
  pl: 'Polish',
  ps: 'Pushto',
  pt: 'Portuguese',
  qu: 'Quechua',
  rm: 'Romansh',
  rn: 'Rundi',
  ro: 'Romanian',
  ru: 'Russian',
  rw: 'Kinyarwanda',
  sa: 'Sanskrit',
  sc: 'Sardinian',
  sd: 'Sindhi',
  se: 'Northern Sami',
  sg: 'Sango',
  si: 'Sinhala',
  sk: 'Slovak',
  sl: 'Slovenian',
  sm: 'Samoan',
  sn: 'Shona',
  so: 'Somali',
  sq: 'Albanian',
  sr: 'Serbian',
  ss: 'Swati',
  st: 'Sotho, Southern',
  su: 'Sundanese',
  sv: 'Swedish',
  sw: 'Swahili',
  ta: 'Tamil',
  te: 'Telugu',
  tg: 'Tajik',
  th: 'Thai',
  ti: 'Tigrinya',
  tk: 'Turkmen',
  tl: 'Tagalog',
  tn: 'Tswana',
  to: 'Tonga',
  tr: 'Turkish',
  ts: 'Tsonga',
  tt: 'Tatar',
  tw: 'Twi',
  ty: 'Tahitian',
  ug: 'Uighur',
  uk: 'Ukrainian',
  ur: 'Urdu',
  uz: 'Uzbek',
  ve: 'Venda',
  vi: 'Vietnamese',
  vo: 'Volapük',
  wa: 'Walloon',
  wo: 'Wolof',
  xh: 'Xhosa',
  yi: 'Yiddish',
  yo: 'Yoruba',
  za: 'Zhuang',
  zh: 'Chinese',
  zu: 'Zulu',
};

export const likeSentData = [
  {
    id: 1,
    image: imageRegistry.tempUser1,
    interaction: InteractionsEnums.LIKE,
    hoursLeft: 12,
  },
  {
    id: 2,
    image: imageRegistry.tempUser2,
    interaction: InteractionsEnums.SUPERLIKE,
    hoursLeft: 8,
  },
  {
    id: 3,
    image: imageRegistry.tempUser3,
    interaction: InteractionsEnums.LIKE,
    hoursLeft: 6,
  },
  {
    id: 4,
    image: imageRegistry.tempUser4,
    interaction: InteractionsEnums.SUPERLIKE,
    hoursLeft: 10,
  },
  {
    id: 5,
    image: imageRegistry.tempUser5,
    interaction: InteractionsEnums.LIKE,
    hoursLeft: 4,
  },
  {
    id: 6,
    image: imageRegistry.tempUser6,
    interaction: InteractionsEnums.SUPERLIKE,
    hoursLeft: 14,
  },
  {
    id: 7,
    image: imageRegistry.tempUser7,
    interaction: InteractionsEnums.LIKE,
    hoursLeft: 2,
  },
  {
    id: 8,
    image: imageRegistry.tempUser8,
    interaction: InteractionsEnums.SUPERLIKE,
    hoursLeft: 16,
  },
];
export const likeReceiveData = [
  {
    id: 1,
    image: imageRegistry.tempUser1,
    interaction: InteractionsEnums.LIKE,
    hoursLeft: 5,
  },
  {
    id: 2,
    image: imageRegistry.tempUser2,
    interaction: InteractionsEnums.SUPERLIKE,
    hoursLeft: 18,
  },
  {
    id: 3,
    image: imageRegistry.tempUser3,
    interaction: InteractionsEnums.LIKE,
    hoursLeft: 9,
  },
  {
    id: 4,
    image: imageRegistry.tempUser4,
    interaction: InteractionsEnums.SUPERLIKE,
    hoursLeft: 3,
  },
  {
    id: 5,
    image: imageRegistry.tempUser5,
    interaction: InteractionsEnums.LIKE,
    hoursLeft: 21,
  },
  {
    id: 6,
    image: imageRegistry.tempUser6,
    interaction: InteractionsEnums.SUPERLIKE,
    hoursLeft: 11,
  },
  {
    id: 7,
    image: imageRegistry.tempUser7,
    interaction: InteractionsEnums.LIKE,
    hoursLeft: 7,
  },
  {
    id: 8,
    image: imageRegistry.tempUser8,
    interaction: InteractionsEnums.SUPERLIKE,
    hoursLeft: 15,
  },
];
